# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5692ac16f3a24e9445bac266569f266463e50e512bdd663b50f40a242029311a8ce819f535590ffb9249cda5434c6cfa631f40f0fe6a30c7742a2e8039e47f0

test:
  secret_key_base: 8dad190485ed3cf3911545860eed1ebae76f2efb16f7065701d2a386f1c156974529e0fdfc45f4cded59c792e1a4e15244945d98c9a2ba00b05e2ed41acc1c36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
